#!/bin/bash

# Here we have a Perl script that invokes grep in a background, 
# Program checks every outputted mac - if it's inside excluded list ./myExcludedList.txt
# wash output is previously splitted to fragments by Perl split funtion (using space as a separator), 
# first part of splitted string is a MAC address of every AP,
# grep command invoked by Perl that uses backticks looks like: grep "00:11:22:33:44:55" ./myExcludedList.txt 2>/dev/null

# tries to extract monitor name from the ifconfig output
getMonitorName(){
    ifconfig | perl -lane '{ if(/^[^\s]*mon/){ $_ =~ s/\s+.*//; print $_; } }'
}

if [[ "$1" == "NO_EXCLUDED" ]]; then
  echo "No excluded list provided, searching all access points."
  wash -i $(getMonitorName) -C -s
elif [[ ! -z "$1" && -f "$1" ]]; then
  echo "Excluded list provided, searching access points without those in file: $1"
  wash -i $(getMonitorName) -C -s  | perl -lane '{ if(length($_)>17) { @x=split " ", $_; $mac=$x[0]; $res=`grep "$mac" '$1' 2>/dev/null`; if(length($res)>17){  } else{ print $_; } }   }'
else
  echo 'You can use a file containing access points list that you want to EXCLUDE from wash search,'
  echo '(format must be the same as apTargets.txt list)'
  echo 'You can then type: '$0' [PATH_TO_EXCLUDED_APs_FILE]'
  echo 'Example: '$0' ./myExcludedList.txt'
  echo '---------------------------------------------'
  echo "If you don't want to use excluded ap's list, just type:"
  echo "$0 NO_EXCLUDED"
fi



